---
language: ruby
bundler_args: --without acceptance
script: "bundle exec rake test SPEC_OPTS='--format documentation'"
rvm:
  - 2.0.0
  - 2.1.0
  - 2.2.0
env:
  - PUPPET_GEM_VERSION="~> 4.2"
  - PUPPET_GEM_VERSION="~> 4.3"
  - PUPPET_GEM_VERSION="~> 4.4"
  - PUPPET_GEM_VERSION="~> 4.5"
matrix:
  fast_finish: true
  exclude:
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 4.2"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 4.3"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 4.4"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 4.5"
